### ISSUE TITLE
Vaulting through spaces you can't fit through

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#388] opened 2023-10-23 02:18 UTC
Essentially - you can reliably vault through spaces your character can't fit through as long as your character fits at the landing spot.

Example 1... Separated stairs with complex collision: from underneath, you can vault through them and appear on top.

Example 2... Barn with wood slats for roof. You cannot fall down through the slats because there's not enough space, but you can vault from below to the roof through the gaps.

**Comment by Sixze** [comment] 2023-10-23 10:33
Could you please provide me with mesh assets that I can test this on?

**Comment by xkamronx** [comment] 2023-10-23 22:10
I have attached the bar with the open roof. When set to Use Complex Collision as Simple (I do this for most buildings for accuracy of geometry, maybe that's bad), you can vault through these areas from underneath, but not fall through them.

The issue is worse if you increase the capsule size of your character, as it doesn't seem to increase the vault size. This is probably a setting in the settings that I haven't messed with, but at the default capsule size this area can be vaulted out of, but you can't fall in to it.

![image](https://github.com/Sixze/ALS-Refactored/assets/26638814/8fb1ff39-5c62-4c84-b257-f6c09df87b9a)
https://drive.google.com/file/d/1VO6uFO_GSFKHy8jZWh6lyH1gbX7Dc34l/view?usp=sharing
(can't upload FBX here I guess so link above)

**Comment by Sixze** [comment] 2023-10-24 21:44
Can't reproduce this issue. Do you have the latest changes of this plugin from the repository? Maybe you can provide me with a video of this issue?

I've tried to mantle from inside the barn in the location shown in your screenshot, but no luck, while in the other, wider two locations, I can because there's actually enough room for the capsule.

Make sure that if you want to scale the character, you change the scale of the capsule component, not its size, in which case the mantling traces will be scaled accordingly.

Also in this case it's better not to use "Use Complex Collision as Simple", because as you can see, even character movement can't work with it correctly.

**Comment by xkamronx** [comment] 2023-10-25 01:33
I have slightly increased the height that the player can actually vault which is likely why you can't reproduce in a default project, sorry about that, totally spaced it. Mine is about 30 units higher than the default settings in the plugin.

The other two spots on the barn you can indeed fall through at the default capsule size. Changing just the capsule diameter messes with the vaulting setup?

**Comment by Sixze** [comment] 2023-10-26 21:51
Should be fixed in 9302e047af0b28260b6e2b3f212faa5c393822e8.

> Changing just the capsule diameter messes with the vaulting setup?

Yes, most all settings are configured with the absolute size of the capsule in mind.

**Closed by Sixze** 2023-10-26 21:51 UTC

**Comment by xkamronx** [comment] 2023-10-28 00:57
> Should be fixed in [9302e04](https://github.com/Sixze/ALS-Refactored/commit/9302e047af0b28260b6e2b3f212faa5c393822e8).
> 
> > Changing just the capsule diameter messes with the vaulting setup?
> 
> Yes, most all settings are configured with the absolute size of the capsule in mind.

Thank you for the information. I was unaware that the mantling mechanic didn’t use the capsule diameter itself. I have currently reverted back to using the default 30.
