### ISSUE TITLE
After mantling, held items often disappear

### ISSUE THREAD

**Issue by kriNon** [Sixze/ALS-Refactored#40] opened 2021-11-20 08:14 UTC
If you hold an item then try to mantle an object, the item being held gets hidden during the mantle animation.
Upon finishing the mantle animation the item normally gets un-hidden.

Sometimes the item does not get un-hidden. After some quick testing, I believe the issue is related to packet loss.

**Comment by Sixze** [comment] 2021-11-20 16:54
Hi, thanks for feedback, I looked at the reason and in fact the problem is somewhat more serious: sometimes, due to lags or packet loss, the server can force change client's `MovementMode`, which leads to the interruption of mantling and other problems, including disappearance of the held item.

At the moment, I am busy with a deeper study of the `CharacterMovementComponent`, in particular in order to improve mantling and reduce character jitter, so the fix will be later along with other `CharacterMovementComponent` improvements.

**Comment by kriNon** [comment] 2021-11-21 03:53
I will look forward to your changes to the CMC.
Thanks for all of the high quality work that you do on this project, this project is an incredible starting point and has saved me an incredible amount of time in my personal project.

**Comment by Sixze** [comment] 2021-12-04 14:18
Fixed in 6ae38c7bfa1f6474e0f73961465d78d65b83e4f7.

**Closed by Sixze** 2021-12-04 14:18 UTC
