### ISSUE TITLE
Ragdolling Issue

### ISSUE THREAD

**Issue by Ivann97** [Sixze/ALS-Refactored#224] opened 2023-01-10 20:34 UTC
Hello,
I found a bug when you ragdoll in the air and stop the ragdoll just before touching the ground.
The issue is simply fixed by removing the AnimNotify_FinalizeRagdolling from the AnimBp, and calling FinalizeRagdolling directly after changing LocomotionAction.
So I wonder if this is really a bug, I think that by playing with the update distances of the animations there would also be a way to solve it. Is there any particular reason to call this function from an AnimNotify?

https://user-images.githubusercontent.com/56310194/211656086-ad6f6e0d-b270-42fc-a46c-b73752a56618.mp4

**Comment by Sixze** [comment] 2023-03-04 14:18
I can't reproduce the bug. Could you provide more details, like have you modified the plugin? what multiplayer options do you use? and etc.

**Comment by Ivann97** [comment] 2023-03-05 16:08
Video  was taken with freshly downloaded and unmodified plugin, everything was default settings, to make sure it was not due to my modifications.
To reproduce the problem use NETMODE_Client with two clients:
-Make sure Client2 is kinda far away from client 1 and looking in the opposite direction
-Client 1 jumps and goes into ragdoll
-Client 1 cancels ragdoll before touching the ground


If I remember correctly, you could also reproduce it this way: 
-client 2 goes far away
-client 1 quickly goes to ragdoll->stop ragdoll
-client 1 tries to mantle something


My guess is that anim notify aren't always called but I am not entirely sure of it (if this is the case with anim montages notifies, why wouldn't it be the case with anim instances one ? Maybe the same happened here: https://forums.unrealengine.com/t/anim-notify-not-firing-not-sure-why/253173 ). I think it is more robust to call the function directly from cpp.

**Comment by Sixze** [comment] 2023-03-06 13:34
Should be fixed in 1d57223d7f378c6d4ffe912b3e5f8ecdf3021f3d.

The `AnimNotify_FinalizeRagdoling` hack existed because it fixed another issue that caused the character mesh to take an odd pose for one frame when transitioning from a ragdoll state to an animation state.

I haven't been able to get rid of this hack completely, but I moved the `AAlsCharacter::FinalizeRagdolling()` call from `AnimNotify_FinalizeRagdoling` to `UAlsAnimationInstance::NativeUpdateAnimation` so the character should no longer get stuck in ragdolling mode.

**Closed by Sixze** 2023-03-06 13:34 UTC
