### ISSUE TITLE
Set Actor Location from Server doesn't always work until Player jumps?

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#406] opened 2023-11-20 19:57 UTC
Not positive of the root cause at the moment.

I run Set Actor Location from the server when loading a player save. Many times, a client will join, it will run Set Actor Location, but it doesn't move the player until they jump. They can run around all over, but as long as they don't jump, it doesn't move them to the correct location.

I have Teleport checked in the Set Actor Location node.

Will test in a default project if needed, but should be reproduceable in a default project running from the server on begin play.

**Comment by xkamronx** [comment] 2023-11-20 20:18
I believe the issue could also stem from not running the function as reliable from the server side.

**Comment by xkamronx** [comment] 2024-03-20 18:44
I ended up just removing the teleport / set actor location nodes entirely and spawning the character at the location instead because it doesn't seem easily fixable - not positive what causes it to not accept the changed position until jumping, but causes a lot of gameplay issues (like the player being invisible to other players) and log spam of invalid movement timestamps.

**Comment by Sixze** [comment] 2024-04-21 21:38
Where exactly are you calling the `SetActorLocation()` function from? I tried calling it from `AAlsCharacter::BeginPlay()` but didn't encounter any issues.

**Comment by Sixze** [comment] 2024-04-27 17:01
Still can't reproduce, and I'm not sure if this problem is ALS related, since it doesn't control the character's location in most cases.

I'll probably close this issue until more details become available.

**Comment by xkamronx** [comment] 2024-04-30 22:37
Understandable.

I'm currently moving more towards the issue being "high ping" as in the 150-300 range causing more of these issues than anything else.

Simulating ping in the default project, it's very easy to get the Timestamp expired spam which causes a lot of other issues.

LogNetPlayerMovement: Warning: ServerMove: TimeStamp expired: 26.517168, CurrentTimeStamp: 28.438307, Character: BP_Player_C_0
LogNetPlayerMovement: Warning: ServerMove: TimeStamp expired: 26.517168, CurrentTimeStamp: 28.461296, Character: BP_Player_C_0
LogNetPlayerMovement: Warning: ServerMove: TimeStamp expired: 26.517168, CurrentTimeStamp: 28.498211, Character: BP_Player_C_0
LogNetPlayerMovement: Warning: CreateSavedMove: Hit limit of 96 saved moves (timing out or very bad ping?)

**Comment by xkamronx** [comment] 2024-05-31 06:51
Still haven't been able to find the cause and solution for the timestamp errors. Seems like a dice roll on whether a player joining a server / multiplayer session will get a good connection or not. If they don't, the timestamp errors flood the log until they reconnect and anything that is reliant on their location being accurate doesn't work.

Usually just leaving and rejoining that session will fix it.

My flow is player joins > controller gets location of their character from a save file > spawn actor using the transform from the save file on server > possess the spawned player.

**Closed** 2024-08-14 15:55 UTC
