### ISSUE TITLE
Character jitters while turning in first-person view.

### ISSUE THREAD

**Issue by Alex-G** [Sixze/ALS-Refactored#45] opened 2021-12-09 21:18 UTC
reproduction:
- play as a client
- set first-person view
- don't aim
- look down
- turn

**Comment by Sixze** [comment] 2021-12-10 15:30
Checked on UE 4.26 and found no problems.

In first-person mode, the camera is attached directly to the character's head and moves with it in animations, maybe this confuses you?

**Comment by Alex-G** [comment] 2021-12-10 19:05
https://user-images.githubusercontent.com/5215249/145628013-a1502c6d-75ea-4578-b1a1-1d1f36f6f8ba.mp4

I use UE 4.27.2

**Comment by Sixze** [comment] 2021-12-10 20:32
I'll check it out later in UE 5.0 EA. If everything is in order in this version, then most likely I will postpone this problem until the full release of UE 5.

**Comment by Sixze** [comment] 2021-12-11 10:06
Tested on UE 5.0 EA with bad network conditions, still no issues.

Have you tested the plugin on UE 4.27.1 before? Were there similar issues?

**Comment by Alex-G** [comment] 2021-12-11 10:36
Sadly I don't know, I checked it on a fresh UE5 project and I can reproduce it.
If you have time let's chat on Discord: Alex-G91#9143

**Comment by Sixze** [comment] 2021-12-11 10:53
Maybe there are some special conditions under which this bug appears?

Can you tell me more about your steps using a fresh UE 5.0 EA project? Or you can send me your minimal example project on which the bug is reproduced.

**Comment by Alex-G** [comment] 2021-12-11 13:03
sure I can do it later.

can you try it with this reproduction:
run the following `cmd` command's (change the path's to yours)

1. `start "Server" "E:\UE_5.0EA\Engine\Binaries\Win64\UnrealEditor.exe" "G:\ALSUE5\ALSUE5.uproject" -server -log -nosteam`
2. `start "Client" "E:\UE_5.0EA\Engine\Binaries\Win64\UnrealEditor.exe" "G:\ALSUE5\ALSUE5.uproject" 127.0.0.1 -game -ResX=1280 -ResY=600 -WinX=20 -WinY=20 -nosteam -WINDOWED`

**Comment by Alex-G** [comment] 2021-12-11 13:18
https://user-images.githubusercontent.com/5215249/145677675-1b98f4a5-3cfd-4a79-a9b5-527578fd9ef0.mp4

another issue is that the chatacter turn's two times to rotate in the view direction.

**Comment by Sixze** [comment] 2021-12-12 10:07
> sure I can do it later.
> 
> can you try it with this reproduction: run the following `cmd` command's (change the path's to yours)
> 
> 1. `start "Server" "E:\UE_5.0EA\Engine\Binaries\Win64\UnrealEditor.exe" "G:\ALSUE5\ALSUE5.uproject" -server -log -nosteam`
> 2. `start "Client" "E:\UE_5.0EA\Engine\Binaries\Win64\UnrealEditor.exe" "G:\ALSUE5\ALSUE5.uproject" 127.0.0.1 -game -ResX=1280 -ResY=600 -WinX=20 -WinY=20 -nosteam -WINDOWED`

It looks like there really is such a bug, even in UE 4.26, but only if you start the game in this way.

**Comment by Sixze** [comment] 2021-12-12 14:42
@Alex-G Could you please add this to your `DefaultEngine.ini` file and test this issue again?

```ini
[SystemSettings]
p.NetEnableMoveCombining=0 
```

**Comment by Alex-G** [comment] 2021-12-12 14:52
shot test, the issue is gone

**Comment by Sixze** [comment] 2021-12-12 15:11
Weird. Without this fix, the client for some reason mostly ignores local rotation if the game is running outside the editor.

**Comment by Sixze** [comment] 2021-12-12 17:48
Fixed in 172f5671eba48172d9bdbaaa8fde78bc4a6dcde0.

`p.NetEnableMoveCombining=0` is required until I figure out how to fix this issue in another way.

**Closed by Sixze** 2021-12-12 17:48 UTC

**Comment by Sixze** [comment] 2022-01-21 17:19
Fixed this bug using a more correct approach, see 36bafc11abc814e8abe968cf679cb708781de066.

`p.NetEnableMoveCombining=0` is no longer required and can be safely removed.
