### ISSUE TITLE
Iris rotation bug

### ISSUE THREAD

**Issue by xkamronx** [Sixze/ALS-Refactored#463] opened 2024-03-20 18:30 UTC
Didn't notice this before using Iris, but after enabling Iris, there is sometimes a bug where the character's rotation doesn't match their actual rotation. The character always faces the same direction, and doing things like vaulting, crouching, etc. don't update on other players screens.

There are a few errors when starting a dedicated server with Iris + ALS Refactored in regards to net serialization.

Not positive how to force this to happen at the moment, working on that, but figured I would report it here since Iris is going to be used more and more as it becomes the default for the Engine within the next few versions.

**Comment by Sixze** [comment] 2024-04-27 16:53
I've added basic Iris support and the only issues I've encountered are the get up animations not playing on clients and an error saying that `B_Als_PlayerController` is not replicated. I fixed the first issue, but not the second, as it seems to be an internal Iris bug.

As for the rotation, ALS just ignores the replicated rotation on clients and instead controls it by itself, so I'm not sure if this issue is specific to Iris or not.

And to emphasize, Iris is still experimental, so I'm not sure if these are ALS bugs or not.

I'm closing this issue for now. If you manage to **reliably** reproduce these or new bugs, feel free to open new issues.

**Closed by Sixze** 2024-04-27 16:53 UTC
